### PR TITLE
fixing the build after repo move

### PR DESCRIPTION
**Pull request by sebs**
The build works again 

* the name of the repo and the package name got out of sync.

### CODE REVIEW

**Comment by Diogenesthecynic** [comment]
Good catch! I've yet to add unit testing / etc., but will eventually.

**Comment by sebs** [comment]
ah. I am writing bdd styled tests in a workshop with participants ;)

**Comment by sebs** [comment]
https://gist.github.com/sebs/58799391bd9a4519a33a

**Comment by sebs** [comment]
This is why I needed the game running. 

Its good material for an exercise: clean code and lots of logic to test.

**Pull request merged**
